import { WorkProject, StudentProject, ServiceItem, ProcessStep, TeamMember } from './types';

export const WORK_PROJECTS: WorkProject[] = [
  {
    id: 'health-kiosk',
    title: 'Smart Privacy Health Kiosk',
    subtitle: 'An IoT-Enabled Automated System for Anonymous Access to Sensitive Healthcare Products',
    category: 'IoT Systems · Mechanical Design · Embedded Firmware · Product Innovation',
    tags: ['IoT Systems', 'Mechanical Design', 'Embedded Firmware', 'Product Innovation'],
    image: '/smart-health-kiosk.jpg',
    description: 'An IoT-enabled, privacy-first automated kiosk designed for 24×7 anonymous access to sensitive healthcare and wellness products (like sanitary pads, pregnancy test kits, and intimate care products), eliminating social stigma and judgment.',
    challenge: 'Designing an Automatic Privacy Packaging System (APPS) and a secure collection locker within a single deployable unit while maintaining reliable multilingual touchscreen control and cashless UPI payments.',
    solution: 'Engineered a custom internal packaging mechanism that bags products automatically before delivery, integrated fingerprint biometrics, RFID maintenance access, low-stock alerts, jam detection, and a remote IoT monitoring dashboard.',
    technologies: ['15-inch Touch UI', 'Automatic Packaging (APPS)', 'ESP32 / STM32', 'UPI Payment Integration', 'Fingerprint Biometrics', 'RFID Access'],
    outcomes: [
      'Awarded ₹2,30,000 PoC grant by SPU-SSIP Navadhārā',
      'Developed Automatic Privacy Packaging System (APPS) for discreet pickup',
      'Integrated 24x7 Emergency Pad Mode for dispensing when payment servers are down',
      'Built remote IoT dashboard for real-time inventory and predictive restocking',
    ],
    featured: true,
  },
  {
    id: 'agri-titan-x6',
    title: 'AGRI-TITAN X6',
    subtitle: 'Smart Modular Precision Agriculture Hexacopter',
    category: 'Drone Engineering · Precision Agriculture · Embedded Systems',
    tags: ['Drone Engineering', 'Precision Agriculture', 'Embedded Systems'],
    badge: 'SSIP-Funded Project',
    image: '/agri-titan-drone-2.png',
    description: 'A heavy-duty smart agricultural hexacopter designed to automate spraying, seeding, and crop protection. Built with a modular plug-and-play payload system, it enables cost-effective precision farming for small and medium-scale fields.',
    challenge: 'Designing a structurally rigid 1200mm hexacopter frame capable of carrying a 10-liter liquid payload (4-6 kg functional weight) while maintaining stable autonomous flight dynamics under variable wind conditions.',
    solution: 'Implemented a Pixhawk autopilot system running ArduPilot flight firmware, a Hobbywing X6 Plus propulsion system, LiDAR-based terrain following, thermal/PIR sensors for night-time wildlife intrusion detection, and a modular pogo-pin connector interface.',
    technologies: ['Pixhawk Autopilot', 'ArduPilot / Mission Planner', 'LiDAR (TFmini-S / TF-Luna)', 'Hobbywing X6 Plus Propulsion', 'Thermal / PIR Sensors', 'Modular Pogo-Pin Connectors'],
    outcomes: [
      'Funded by SSIP 2.0 with a prototype budget estimation of ₹2,42,627',
      'Achieved fully autonomous GPS-based waypoint navigation and terrain-following altitude stabilization',
      'Designed a multi-nozzle 10-liter spraying module and an 8-10 kg PWM-controlled seed broadcasting hopper',
      'Integrated thermal/PIR sensors with siren repeller to reduce crop damage from wildlife by 10-15%',
    ],
    featured: false,
  },
  {
    id: 'smart-print-station',
    title: 'PrintPoint',
    subtitle: '24/7 Self-Service Document & Stationery Vending Kiosk',
    category: 'Embedded Systems · Automation · Web Platform',
    tags: ['Embedded Systems', 'Automation', 'Web Platform'],
    image: '/smart-print-station.png',
    description: 'A 24/7 self-service document kiosk designed to provide round-the-clock access to black & white or color printing, photocopying, scanning, passport photo printing, and integrated stationery vending with secure UPI payments.',
    challenge: 'Integrating robust mechanical vending for office supplies alongside high-speed laser printing, dual-page scanning, and automated post-processing like document stapling and lamination.',
    solution: 'Engineered a custom unattended kiosk enclosure housing a passport photo printer, stationery vending spiral tracks, a touch control panel for QR document upload, and automatic file deletion for user privacy.',
    technologies: ['Raspberry Pi 4', 'Laser & Thermal Automation', 'UPI Payment Gateway', 'Node.js / React', 'OpenCV Image Processing'],
    outcomes: [
      'Designed modular internal layout for dual-printer, scanner, and stationery dispenser configuration',
      'Supports 24/7 instant printing via WhatsApp, QR upload, or USB drive connection',
      'Implemented a secure collection locker and privacy-first confidential document auto-delete protocol',
      'Integrated multi-size photocopy presets and OCR text extraction capabilities',
    ],
    featured: false,
  },
  {
    id: 'smart-safety-helmet',
    title: 'Smart Safety Helmet',
    subtitle: 'Automatic Smart LED Work Light for Electrical Linemen',
    category: 'Hardware Design · Embedded Systems · Safety Technology',
    tags: ['Hardware Design', 'Embedded Systems', 'Safety Technology'],
    badge: 'State-Level Winning Project',
    image: '/smart-safety-helmet.jpg',
    description: 'A smart safety helmet featuring a microcontroller-free, hardware-driven automatic LED work light designed for GUVNL linemen. It automates illumination dynamically based on darkness and distance to ensure safe, hands-free nighttime power restoration.',
    challenge: 'Designing a robust, ultra-low cost, and energy-efficient control circuit using pure digital logic gates (no microcontroller) while maintaining reliable distance-based beam switching and sensor integration.',
    solution: 'Implemented LDR-based ambient light sensing, IR-based distance detection for automatic high/low beam switching, HR202 humidity sensing for amber light warning, CD4093-based micro flasher circuit for SOS distress signaling, and TP4056-based battery charging.',
    technologies: ['Digital Logic Gates', 'LDR Sensor', 'IR Sensor (HW201)', 'Humidity Sensor (HR202)', 'Micro Flasher (CD4093)', 'TP4056 Power Module'],
    outcomes: [
      'Designed and built prototype at a cost of only ₹423',
      'Successfully bypassed microcontrollers using digital gates, maximizing battery efficiency and ruggedness',
      'Implemented automatic distance-based beam switching (focus vs. spread light)',
      'Integrated independent SOS emergency circuitry that works even if the main lights fail',
    ],
    featured: false,
  },

  {
    id: 'water-leakage-theft',
    title: 'IoT-enabled Water Leakage & Theft Detection System',
    subtitle: 'Prepaid Water Meter, Real-Time Flow & Quality Monitoring, and Mesh Network Telemetry',
    category: 'IoT Systems · Water Tech · Embedded Firmware · Smart Utilities',
    tags: ['IoT Systems', 'Water Tech', 'Embedded Firmware', 'Smart Utilities'],
    badge: 'National Level Runner Up Project',
    image: '/water-leakage-theft.jpg',
    description: 'A smart prepaid IoT water meter system featuring a 3-device ecosystem (User Meter, Society Node, and Government Unit) designed for the BGI Hackathon 2026. It monitors water quantity and quality (TDS, Turbidity, pH) in real-time while detecting leakages, pipe cuts, and meter tampering.',
    challenge: 'Detecting micro-leakages, illegal pipe cuts before the meter, and physical meter tampering in real-time while ensuring offline communication reliability in remote areas.',
    solution: 'Engineered a dual-dashboard prepaid water control system utilizing ESP32 microcontrollers, YF-S201 flow sensors, pressure sensors, MPU6050 IMUs for tamper detection, and TDS/Turbidity/pH probes. Implemented an offline-first mesh network (ESP-NOW) with SD storage to sync data when Wi-Fi is unavailable, alongside a manual emergency water reserve trigger.',
    technologies: ['ESP32', 'ESP-NOW Mesh', 'YF-S201 Flow Sensor', 'MPU6050 Accelerometer', 'TDS / Turbidity / pH Sensors', 'PostgreSQL Database'],
    outcomes: [
      'Selected for BGI Hackathon 2026 Theme: Smart Cities & Urban Innovation',
      'Designed a 3-device architecture (User Meter, Society Node, and Government Unit) with sub-1 second response time',
      'Built a prepaid recharge system with offline emergency override buttons',
      'Successfully combined water quality metrics (TDS, pH) with volume tracking in a single smart meter',
    ],
    featured: false,
  },
  {
    id: 'density-traffic-controller',
    title: 'Density-Based Traffic Light Controller',
    subtitle: 'Real-Time Traffic Queue Analysis & Adaptive Signal Timing System',
    category: 'Embedded Systems · Smart City · Automation · Computer Vision',
    tags: ['Embedded Systems', 'Smart City', 'Automation', 'Computer Vision'],
    badge: 'Smart City Solution',
    image: '/density-traffic-controller.jpg',
    description: 'An adaptive traffic signal control system utilizing ultrasonic distance sensors, infrared vehicle counters, and camera vision feeds to dynamically adjust green light duration based on real-time junction congestion.',
    challenge: 'Replacing fixed timer traffic signals with low-latency adaptive algorithms to reduce urban traffic gridlock and prioritize emergency vehicles.',
    solution: 'Integrated ultrasonic sensor arrays per lane with microcontroller interrupt timers and custom priority routing for emergency ambulances equipped with RF transponders.',
    technologies: ['Microcontroller Firmware', 'Ultrasonic Sensor Array', 'IR Vehicle Detection', 'Emergency RF Priority Sync', 'Traffic Analytics Portal'],
    outcomes: ['35% reduction in average junction waiting time', 'Automatic priority green corridor for emergency vehicles', 'Field-tested across multi-lane test intersections'],
    featured: false,
  },
];

export const STUDENT_PROJECTS: StudentProject[] = [
  // HARDWARE PROJECTS (Arduino Uno based)
  {
    id: 'arduino-radar-system',
    title: 'Ultrasonic Radar System',
    category: 'Hardware',
    difficulty: 'Beginner',
    price: '₹1,999',
    image: '/arduino-radar.png',
    description: 'A servo-swept obstacle detection radar system utilizing an ultrasonic sensor to map and display distances on a Processing interface.',
    techStack: ['Arduino Uno', 'HC-SR04 Sensor', 'SG90 Servo', 'Processing IDE'],
    includes: ['Complete Arduino Code', 'Processing Screen Script', '3D Enclosure STL File', 'Circuit Schematic'],
    specifications: {
      'Processor': 'ATmega328P (Arduino Uno)',
      'Sensor Range': '2cm to 400cm',
      'Sweeping Angle': '15° to 165°',
      'Visualization': 'Real-time Processing radar UI',
    },
  },
  {
    id: 'arduino-smart-bin',
    title: 'Automatic Smart Dustbin',
    category: 'Hardware',
    difficulty: 'Beginner',
    price: '₹1,499',
    image: '/arduino-smart-bin.png',
    description: 'A touchless smart garbage can that automatically opens its lid when hand proximity is detected, ensuring hygienic disposal.',
    techStack: ['Arduino Uno', 'HC-SR04 Sensor', 'SG90 Servo', 'Battery Management'],
    includes: ['SolidWorks Assembly', 'Arduino Sketch', 'Wiring Schematic', 'BOM Checklist'],
    specifications: {
      'Activation Range': '10cm to 15cm',
      'Servo Angle': '90° (Lid open)',
      'Power Supply': '4x AA Batteries (6V)',
      'Response Time': 'Under 250ms',
    },
  },
  {
    id: 'arduino-bluetooth-car',
    title: 'Bluetooth Controlled RC Car',
    category: 'Hardware',
    difficulty: 'Intermediate',
    price: '₹2,799',
    image: '/arduino-bluetooth-car.png',
    description: 'A 4-wheel drive robotic car controlled remotely via an Android/iOS app over Bluetooth with obstacle detection override.',
    techStack: ['Arduino Uno', 'HC-05 Bluetooth', 'L298N Motor Driver', 'DC Gear Motors'],
    includes: ['Chassis Layout PDF', 'Arduino Firmware', 'Custom Android APK', 'Circuit Diagram'],
    specifications: {
      'Bluetooth Version': 'HC-05 v2.0+EDR',
      'Motor Driver': 'L298N Dual H-Bridge',
      'Motors': '4x DC Gear Motors (6-9V)',
      'Control Protocol': 'UART Serial Commands',
    },
  },
  {
    id: 'arduino-rfid-lock',
    title: 'RFID Smart Door Lock System',
    category: 'Hardware',
    difficulty: 'Intermediate',
    price: '₹2,399',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
    description: 'A secure access control system utilizing RFID cards to trigger a servo/solenoid door lock with an LCD status display.',
    techStack: ['Arduino Uno', 'RC522 RFID Module', '16x2 LCD Display', 'SG90 Servo'],
    includes: ['Gerber PCB Layout', 'Firmware Code', 'RFID Register Script', 'User Manual'],
    specifications: {
      'RFID Frequency': '13.56 MHz',
      'User Capacity': 'Up to 20 registered cards',
      'Lock Type': 'Servo Latch / Solenoid Trigger',
      'Display': '16x2 Character I2C LCD',
    },
  },
  {
    id: 'arduino-drip-irrigation',
    title: 'Smart Plant Drip Irrigation',
    category: 'Hardware',
    difficulty: 'Beginner',
    price: '₹2,199',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80',
    description: 'An automated watering kit that reads soil moisture levels and triggers a mini submersible pump to water plants when dry.',
    techStack: ['Arduino Uno', 'Soil Moisture Sensor', '5V Relay Module', 'Submersible Pump'],
    includes: ['Calibration Guide', 'Arduino Source Code', 'Wiring Blueprint', '3D Case Design'],
    specifications: {
      'Moisture Sensor': 'Corrosion-Resistant Soil Probe',
      'Pump Capacity': '120 L/H (5V DC)',
      'Power Rating': '5V USB or DC Jack',
      'Relay Lifetime': '100,000 Cycles',
    },
  },
  {
    id: 'arduino-alarm-clock',
    title: 'Digital Clock with Temperature',
    category: 'Hardware',
    difficulty: 'Beginner',
    price: '₹1,699',
    image: 'https://images.unsplash.com/photo-1590055531615-f16d36ffe8ec?auto=format&fit=crop&w=600&q=80',
    description: 'A desktop alarm clock displaying real-time clock data (RTC) and room temperature, featuring alarm buzzers and snooze buttons.',
    techStack: ['Arduino Uno', 'DS3231 RTC Module', 'DHT11 Temp Sensor', '16x2 LCD'],
    includes: ['Schematic Blueprint', 'Arduino Library Set', 'Code Files', 'Laser-Cut Case Files'],
    specifications: {
      'Time Keeping': 'DS3231 High-Precision RTC',
      'Sensor': 'DHT11 Temperature & Humidity',
      'Accuracy': '±2 Seconds per Month',
      'Alarms': 'Configurable Buzzer Active Alarms',
    },
  },
  {
    id: 'arduino-laser-alarm',
    title: 'Laser Tripwire Security Alarm',
    category: 'Hardware',
    difficulty: 'Beginner',
    price: '₹1,399',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
    description: 'A home security alarm that triggers a loud buzzer and blinking LEDs if a focused laser beam tripwire is broken by an intruder.',
    techStack: ['Arduino Uno', 'LDR Photoresistor', 'Active Buzzer', 'Laser Diode'],
    includes: ['Calibration Checklist', 'Arduino Code Sketch', 'Circuit Diagrams', 'Enclosure Assembly Guide'],
    specifications: {
      'Tripwire Range': 'Up to 10 Meters',
      'Light Sensor': 'LDR Photoresistor (5516)',
      'Alarm Outputs': '85dB Active Buzzer + Red LED',
      'Power Consumption': '<50mA at 5V',
    },
  },
  {
    id: 'arduino-line-follower',
    title: 'Automatic Line Follower Robot',
    category: 'Hardware',
    difficulty: 'Intermediate',
    price: '₹2,999',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=600&q=80',
    description: 'A mobile autonomous robot that tracks and follows black lines on a light floor surface using dual IR sensor reflection tracking.',
    techStack: ['Arduino Uno', 'Dual IR Sensors', 'L298N Driver', 'BO Motors'],
    includes: ['Sensor Alignment Guide', 'Robotic Chassis Templates', 'Arduino Code', 'Wiring Layout'],
    specifications: {
      'Sensors': '2x TCRT5000 IR Reflectors',
      'Chassis': 'Laser-Cut 2WD Acrylic Chassis',
      'Response Speed': 'Sub-10ms Sensor Polling Rate',
      'Battery': '2x 18650 Li-ion Batteries (8.4V)',
    },
  },
  {
    id: 'arduino-smart-home',
    title: 'IR Remote Home Appliance Control',
    category: 'Hardware',
    difficulty: 'Intermediate',
    price: '₹2,499',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
    description: 'A home automation unit that controls AC light bulbs and fans using a standard TV remote control via an infrared receiver.',
    techStack: ['Arduino Uno', 'IR Receiver Module', '4-Channel Relay Board', 'IR TV Remote'],
    includes: ['Optocoupled Safety Guide', 'Source Code', 'Connection Schematics', 'PCB Gerber Files'],
    specifications: {
      'AC Relays': '4 Channels Optocoupled (250V 10A)',
      'Receiver': 'VS1838B IR Sensor (38kHz)',
      'Remote Range': 'Up to 8 Meters Line-of-Sight',
      'Command Storage': 'EEPROM Preset Mapping',
    },
  },
  {
    id: 'arduino-tft-paint',
    title: 'TFT Touch Screen Paint Pad',
    category: 'Hardware',
    difficulty: 'Advanced',
    price: '₹3,499',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80',
    description: 'An interactive digital drawing pad utilizing a 2.4-inch resistive touch screen, allowing users to draw with custom color palettes.',
    techStack: ['Arduino Uno', '2.4" TFT Touch Shield', 'SPFD5408 Controller', 'Adafruit GFX'],
    includes: ['Touch Calibration Script', 'Arduino Code', 'Drawing GUI Interface', 'Stylus Pen Blueprints'],
    specifications: {
      'Display Size': '2.4-Inch Diagonal',
      'Resolution': '240 x 320 Pixels',
      'Color Depth': '16-Bit Color (65k Colors)',
      'Touch Interface': 'Resistive Touch Panel Overlay',
    },
  },

  // SOFTWARE PROJECTS
  {
    id: 'pavanputra-cinematic',
    title: 'Pavanputra-Cinematic',
    category: 'Software',
    difficulty: 'Advanced',
    price: '₹8,999',
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=600&q=80',
    description: 'High-performance 3D WebGL cinematic video streaming showcase platform with dynamic particle shaders, custom media player, and rich UI animation.',
    techStack: ['React', 'Three.js / WebGL', 'Framer Motion', 'Tailwind CSS', 'Node.js'],
    includes: ['Complete React + Three.js Source Code', 'WebGL Custom Shaders', 'Responsive UI Kit', 'Production Build Script'],
    specifications: {
      '3D Engine': 'Three.js / WebGL Canvas',
      'Framework': 'React + TypeScript',
      'Performance': '60 FPS Smooth Render',
      'Styling': 'Custom Tailwind System',
    },
  },
  {
    id: 'janvote',
    title: 'JanVote',
    category: 'Software',
    difficulty: 'Advanced',
    price: '₹9,999',
    image: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?auto=format&fit=crop&w=600&q=80',
    description: 'Secure digital voting and civic polling web portal featuring cryptographic ballot encryption, biometrics verification, and real-time tally dashboard.',
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'CryptoWeb API'],
    includes: ['Full Stack Web Source Code', 'Database Schema SQL', 'Cryptographic Verification Docs', 'Admin Dashboard'],
    specifications: {
      'Auth System': 'JWT + Biometric / OTP Verification',
      'Encryption': 'SHA-256 Encrypted Ballots',
      'Database': 'PostgreSQL + Prisma',
      'Architecture': 'Next.js App Router',
    },
  },
  {
    id: 'crowdshield',
    title: 'CrowdShield',
    category: 'Software',
    difficulty: 'Intermediate',
    price: '₹7,999',
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=600&q=80',
    description: 'Real-time AI crowd density analytics and emergency dispatch monitoring platform with live heatmap streaming and automated threshold alerts.',
    techStack: ['Python', 'FastAPI', 'OpenCV', 'React', 'WebSockets'],
    includes: ['Python AI Analytics API', 'React Heatmap Dashboard', 'WebSocket Live Stream', 'Deployment Docker Config'],
    specifications: {
      'Analytics Engine': 'OpenCV + YOLOv8 Detection',
      'Streaming': 'WebSockets Latency <100ms',
      'Frontend': 'React Dashboard + Leaflet',
      'Backend': 'FastAPI Microservice',
    },
  },
  {
    id: 'mindsync',
    title: 'MindSync',
    category: 'Software',
    difficulty: 'Intermediate',
    price: '₹6,999',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=600&q=80',
    description: 'AI-powered collaborative workspace platform combining smart markdown notes, real-time audio rooms, and AI document summarization.',
    techStack: ['React', 'WebRTC', 'Tailwind CSS', 'Node.js', 'OpenAI API'],
    includes: ['React Workspace Frontend', 'WebRTC Peer Audio Engine', 'OpenAI Assistant Router', 'Docker Environment'],
    specifications: {
      'Collaboration': 'Real-Time WebSockets Sync',
      'Audio Tech': 'WebRTC Mesh Network',
      'AI Model': 'GPT-4o Document Engine',
      'Storage': 'Redis + MongoDB',
    },
  },
  {
    id: 'moodwave',
    title: 'MoodWave',
    category: 'Software',
    difficulty: 'Beginner',
    price: '₹5,999',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
    description: 'Personal mental wellness and emotion tracking web application with interactive canvas audio visualizer and AI mood analytics.',
    techStack: ['React', 'Web Audio API', 'Chart.js', 'Tailwind CSS'],
    includes: ['Complete React App Code', 'Web Audio Visualizer Component', 'Chart Analytics Suite', 'Local-Storage Offline Sync'],
    specifications: {
      'Audio Tech': 'HTML5 Web Audio API',
      'Analytics': 'Chart.js Dynamic Graphs',
      'Storage': 'Local-First IndexDB',
      'UI Framework': 'Tailwind CSS',
    },
  },
  {
    id: 'vaultone',
    title: 'VaultOne',
    category: 'Software',
    difficulty: 'Advanced',
    price: '₹9,499',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80',
    description: 'Zero-knowledge end-to-end encrypted password and sensitive document vault with master key derivative cryptography and cross-device sync.',
    techStack: ['TypeScript', 'React', 'WebCrypto API', 'Electron', 'Node.js'],
    includes: ['React & Electron Web Desktop Code', 'WebCrypto Vault Core', 'Cross-Device Sync API', 'Security Audit Blueprint'],
    specifications: {
      'Encryption': 'AES-256-GCM + PBKDF2',
      'Zero-Knowledge': 'Client-Side Encryption Only',
      'Target': 'Web + Desktop App',
      'Database': 'Encrypted SQLite',
    },
  },
  {
    id: 'dayflow-hrms',
    title: 'Dayflow — Human Resource Management System (8-hours)',
    category: 'Software',
    difficulty: 'Intermediate',
    price: '₹10,499',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=600&q=80',
    description: 'Full enterprise HRMS web application featuring automated 8-hour shift tracking, leave approvals, payroll generation, and employee analytics.',
    techStack: ['Next.js', 'TypeScript', 'Prisma ORM', 'PostgreSQL', 'Tailwind CSS'],
    includes: ['Full Next.js App Source Code', 'Prisma Database Schema', 'Payroll Generator Engine', 'Role-Based Dashboard'],
    specifications: {
      'Framework': 'Next.js App Router',
      'Database': 'PostgreSQL + Prisma',
      'Attendance Tech': 'Geo-Fenced Shift Clocking',
      'Role Control': 'Super Admin / HR / Employee',
    },
  },
  {
    id: 'facenation',
    title: 'FaceNation',
    category: 'Software',
    difficulty: 'Advanced',
    price: '₹9,799',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    description: 'Facial recognition automated attendance and security access web portal powered by face-api.js neural networks and webcams.',
    techStack: ['React', 'Face-API.js', 'TensorFlow.js', 'Node.js', 'Express'],
    includes: ['React Facial Recognition Code', 'Pre-trained Face Models', 'Node.js Backend API', 'Exportable Attendance CSV Engine'],
    specifications: {
      'AI Engine': 'TensorFlow.js + Face-API',
      'Accuracy': '98.2% Facial Verification',
      'Speed': '<200ms Frame Detection',
      'Storage': 'Encrypted Vector Embeddings',
    },
  },
  {
    id: 'eventify',
    title: 'Eventify',
    category: 'Software',
    difficulty: 'Intermediate',
    price: '₹7,299',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=600&q=80',
    description: 'All-in-one event management platform for ticketing, dynamic QR code badge generation, schedule management, and attendee check-ins.',
    techStack: ['React', 'Node.js', 'Express', 'MongoDB', 'QR Code Generator'],
    includes: ['Full Eventify Portal Source Code', 'QR Ticket Verification Scanner', 'MongoDB Database Models', 'Stripe Payment Hook'],
    specifications: {
      'Ticketing': 'Automated Dynamic QR Pass',
      'Backend': 'Node.js Express REST API',
      'Database': 'MongoDB Atlas',
      'Payment': 'Integrated Checkout',
    },
  },
  {
    id: 'huddle',
    title: 'Huddle',
    category: 'Software',
    difficulty: 'Intermediate',
    price: '₹7,799',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80',
    description: 'Developer community platform featuring real-time group chat rooms, code snippet sharing with syntax highlighting, and virtual audio spaces.',
    techStack: ['React', 'Socket.io', 'Node.js', 'Tailwind CSS', 'Prism.js'],
    includes: ['React Chat Application Code', 'Socket.io WebSocket Server', 'Syntax Highlighter Integration', 'UI Component Kit'],
    specifications: {
      'Real-Time Engine': 'Socket.io WebSockets',
      'Syntax Highlighting': 'Prism.js Code Blocks',
      'Frontend': 'React + Tailwind CSS',
      'State': 'Redux Toolkit / Context',
    },
  },
  {
    id: 'campus-flow',
    title: 'Campus-Flow',
    category: 'Software',
    difficulty: 'Beginner',
    price: '₹6,499',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=600&q=80',
    description: 'Smart college campus utility app for classroom booking, bus schedule tracking, assignment submissions, and student noticeboard.',
    techStack: ['React', 'PostgreSQL', 'Tailwind CSS', 'Progressive Web App'],
    includes: ['React PWA Web Source Code', 'PostgreSQL Authentication & RLS Rules', 'Interactive Campus Map Component', 'PWA Manifest Setup'],
    specifications: {
      'PWA Support': 'Offline-First Service Worker',
      'Database': 'PostgreSQL Realtime DB',
      'Authentication': 'Google OAuth + Student ID',
      'UI Framework': 'Tailwind CSS',
    },
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: 'product-engineering',
    title: 'Product Engineering',
    description: 'End-to-end product architecture, feasibility analysis, system design, functional prototyping, and manufacturing preparation.',
    features: [
      'Discovery & Concept Feasibility',
      'System Architecture & Bill of Materials (BOM)',
      'Rapid Functional Prototyping',
      'Testing & Validation Protocols',
      'DFM (Design for Manufacturing) Handover',
    ],
    cta: 'Discuss a Product Idea →',
    iconName: 'Cpu',
  },
  {
    id: 'mechanical-cad',
    title: 'Mechanical Design & CAD',
    description: 'Industrial design, 3D CAD modeling, complex enclosure design, internal mechanisms, stress simulation, and 3D printing optimization.',
    features: [
      '3D Parametric CAD (SolidWorks/Fusion 360)',
      'Custom Enclosure & Mechanical Mounts',
      'FEA Stress & Thermal Simulation',
      'Tolerance Stackup Analysis',
      'Rapid Prototyping & CNC Machining Prep',
    ],
    cta: 'Start a Mechanical Project →',
    iconName: 'Boxes',
  },
  {
    id: 'electronics-pcb',
    title: 'Electronics & PCB',
    description: 'Custom PCB schematic capture, high-speed multi-layer layout, component selection, signal integrity, and circuit board assembly.',
    features: [
      'Schematic Capture & Component Sourcing',
      'Multi-Layer High-Density PCB Layout',
      'Power Management & Battery Circuits',
      'Sensor Integration & Signal Conditioning',
      'SMD Prototype Assembly & Testing',
    ],
    cta: 'Discuss an Electronics Project →',
    iconName: 'Zap',
  },
  {
    id: 'embedded-iot',
    title: 'Embedded Systems & IoT',
    description: 'Microcontroller firmware development, real-time operating systems (RTOS), IoT connectivity protocols, and sensor telemetry.',
    features: [
      'Firmware (ESP32, STM32, Nordic, Arduino)',
      'FreeRTOS & Embedded C/C++ Optimization',
      'BLE, Wi-Fi, LoRa, MQTT Protocols',
      'Over-The-Air (OTA) Firmware Updates',
      'Low-Power Sleep Modes & Battery Optimization',
    ],
    cta: 'Build an Embedded System →',
    iconName: 'Radio',
  },
  {
    id: 'software-development',
    title: 'Software Development',
    description: 'Full-stack web applications, custom management dashboards, cloud APIs, cross-platform mobile apps, and real-time control panels.',
    features: [
      'React / TypeScript Modern Web Apps',
      'Express & Node.js Backend Microservices',
      'Real-Time WebSocket Data Dashboards',
      'REST & GraphQL API Engineering',
      'Cloud Infrastructure & CI/CD Pipelines',
    ],
    cta: 'Discuss a Software Project →',
    iconName: 'Code2',
  },
  {
    id: 'ai-automation',
    title: 'AI & Automation',
    description: 'Computer vision integration, automated workflow pipelines, smart hardware edge-AI models, and generative AI features.',
    features: [
      'Computer Vision & Object Detection',
      'Edge AI Inference (TensorFlow Lite)',
      'Industrial Process Automation Pipelines',
      'Custom Gemini & LLM AI Integrations',
      'Predictive Maintenance Algorithms',
    ],
    cta: 'Explore AI Solutions →',
    iconName: 'Sparkles',
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: '01',
    title: 'DISCOVER',
    subtitle: 'Understanding Your Vision',
    description: 'We sit down with you to understand exactly what you want to build. We figure out the challenges, set goals, and create a clear step-by-step plan to bring your idea to life.',
    deliverables: ['Product Requirements', 'Technology Plan', 'Project Timeline'],
    shapeType: 'cube',
  },
  {
    number: '02',
    title: 'FEASIBILITY',
    subtitle: 'Proving It Works',
    description: 'Before going all-in, we do quick tests to make sure the idea actually works. We build basic test models, check if parts are available, and estimate how much the final product will cost to make.',
    deliverables: ['Basic Test Model', 'Initial Parts List', 'Cost Estimate'],
    shapeType: 'sphere',
  },
  {
    number: '03',
    title: 'ARCHITECT',
    subtitle: 'Creating The Blueprint',
    description: 'This is where we create the master plan. We map out the internal electronics, figure out how the physical parts will fit together, and plan how the software will communicate with the hardware.',
    deliverables: ['System Blueprint', 'Electronics Plan', '3D Layout'],
    shapeType: 'torus',
  },
  {
    number: '04',
    title: 'DESIGN',
    subtitle: 'Looks & User Experience',
    description: 'We design the look and feel of your product. We create 3D models of the physical casing so it looks great, and we design beautiful digital screens and apps if your product needs them.',
    deliverables: ['3D Product Design', 'Circuit Board Files', 'App/Screen Designs'],
    shapeType: 'octahedron',
  },
  {
    number: '05',
    title: 'PROTOTYPE',
    subtitle: 'Building The First Version',
    description: 'We build the first real version of your product! We 3D-print the casing, put together the custom electronics boards, and load the initial software so we can test the real thing in our hands.',
    deliverables: ['Physical 3D Prototype', 'Custom Electronics Board', 'Basic Software'],
    shapeType: 'ring',
  },
  {
    number: '06',
    title: 'INTEGRATE',
    subtitle: 'Connecting To The Cloud',
    description: 'We connect the physical product to the digital world. We make sure the hardware sensors, the cloud servers, and your mobile apps are all talking to each other perfectly without any delays.',
    deliverables: ['Cloud Connection', 'Control Dashboard', 'Wireless Update System'],
    shapeType: 'pyramid',
  },
  {
    number: '07',
    title: 'TEST & ITERATE',
    subtitle: 'Making It Bulletproof',
    description: 'We push the prototype to its limits. We test it for heat, drop it to check durability, fix any bugs, and keep making improvements until it works flawlessly every single time.',
    deliverables: ['Quality Testing Report', 'Durability Results', 'Final Polished Software'],
    shapeType: 'cylinder',
  },
  {
    number: '08',
    title: 'DELIVER',
    subtitle: 'Handing Over The Keys',
    description: 'You get your finished product. We hand over the fully working physical units, along with all the design files, source code, and manufacturing instructions you need to mass-produce it.',
    deliverables: ['Working Products', 'Manufacturing Guide', 'Full Source Code'],
    shapeType: 'knot',
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'prince-tagadiya',
    initials: 'PT',
    name: 'Prince Tagadiya',
    role: 'Founder, CEO & CPTO',
    department: 'Product · Technology · Business Strategy',
    tags: ['Product Strategy', 'Systems Architecture', 'Hardware R&D', 'Business Lead'],
    bio: 'Visionary engineering lead steering multidisciplinary hardware and software product creation from initial napkin sketch to scaled deployment.',
    expandedBio: 'Prince leads CRETO4\'s overall product roadmap, hardware-software architecture integration, and strategic client ventures. With deep expertise across cross-disciplinary engineering and industrial prototyping, he bridges conceptual client vision into robust physical products.',
    keyContributions: [
      'Architected the Smart Privacy Health Kiosk hardware & cloud pipeline',
      'Spearheaded SSIP Government Innovation Grant acquisition',
      'Directs multidisciplinary R&D across embedded, CAD, and software teams'
    ],
    specialties: ['Cross-disciplinary Systems Architecture', 'Industrial DFM & Rapid Prototyping', 'Venture Strategy & Client Delivery'],
    stats: [
      { label: 'Projects Led', value: '25+' },
      { label: 'R&D Experience', value: '4+ Yrs' },
      { label: 'Grants Secured', value: 'SSIP' }
    ]
  },
  {
    id: 'nisarg-patel',
    initials: 'NP',
    name: 'Nisarg Patel',
    role: 'Head of Electronics, Embedded Systems & Manufacturing',
    department: 'Hardware · Embedded · Electronics Manufacturing',
    tags: ['Hardware Engineering', 'Embedded C++', 'DFM', 'Sensors'],
    bio: 'Expert in high-reliability circuit design, power management, micro-controller firmware, and precision electronics manufacturing pipelines.',
    expandedBio: 'Nisarg leads the physical electronics engineering at CRETO4. From high-current power distribution boards for heavy-payload hexacopters to sub-second sensor telemetry hubs, he ensures ultra-reliable hardware performance under demanding operational environments.',
    keyContributions: [
      'Designed custom PDB and RTK-GPS telemetry for Agri-Titan X6 drone',
      'Developed sub-100mW power management for Smart Safety Helmet',
      'Established in-house SMT assembly & hardware verification protocols'
    ],
    specialties: ['STM32 & ESP32 Embedded C/C++', 'Power Electronics & Battery Systems', 'Sensor Telemetry & RF Communication'],
    stats: [
      { label: 'Custom PCBs', value: '40+' },
      { label: 'Sensor Modules', value: '100+' },
      { label: 'Uptime Rate', value: '99.9%' }
    ]
  },
  {
    id: 'khushi-belani',
    initials: 'KB',
    name: 'Khushi Belani',
    role: 'Head of PCB Design, Education & Brand Communications',
    department: 'PCB Design · Research · QA · Education · Brand',
    tags: ['PCB Layout', 'Signal Integrity', 'Quality Assurance', 'Brand Communication'],
    bio: 'Directs multi-layer PCB layout, component selection, educational project publishing, and technical brand positioning.',
    expandedBio: 'Khushi oversees high-density PCB design standards, electromagnetic compatibility (EMC) compliance, and technical publishing. She also leads CRETO4\'s educational STEM initiative, translating complex hardware designs into accessible learning kits for student engineers.',
    keyContributions: [
      'Published technical research articles in Electronics For You magazine',
      'Engineered multi-layer HDI PCB layouts for IoT diagnostic kiosks',
      'Curated DIY engineering kit documentation and Gerber manufacturing specs'
    ],
    specialties: ['Altium Designer Multi-Layer HDI Routing', 'Signal & Power Integrity Analysis', 'Technical Publishing & Brand Strategy'],
    stats: [
      { label: 'Publications', value: 'Featured' },
      { label: 'PCB Layers', value: '4-6 Layers' },
      { label: 'Kits Created', value: '15+' }
    ]
  },
  {
    id: 'rudra-chauhan',
    initials: 'RC',
    name: 'Rudra Chauhan',
    role: 'Head of Software Engineering & Digital Design',
    department: 'Software · Cloud Infrastructure · Digital Experiences',
    tags: ['Full-Stack Web', 'Cloud Infrastructure', '3D WebGL', 'AI Systems'],
    bio: 'Architects modern cloud applications, real-time IoT web portals, interactive 3D WebGL graphics, and scalable software backends.',
    expandedBio: 'Rudra directs the digital experience engineering at CRETO4. Combining full-stack React/Node web platforms with real-time hardware WebSockets, 3D WebGL visualizations, and modern AI/LLM API integrations, he delivers seamless software control for physical hardware devices.',
    keyContributions: [
      'Built full-stack real-time telemetry dashboard for Smart Health Kiosk',
      'Designed high-performance 3D WebGL interactive product visualizers',
      'Engineered zero-latency MQTT cloud queues for IoT print terminals'
    ],
    specialties: ['React / TypeScript / Vite / WebGL', 'Node.js, WebSockets & MQTT Telemetry', 'Cloud Infrastructure & API Design'],
    stats: [
      { label: 'Web Applications', value: '30+' },
      { label: 'Daily Telemetry', value: '50k+ Events' },
      { label: '3D Assets', value: 'Interactive' }
    ]
  }
];

export const TRUST_ACHIEVEMENTS = [
  { id: '1', label: 'SSIP FUNDED', detail: 'Government Student Startup & Innovation Policy Grant Recipient for Agriculture Drone Innovation.' },
  { id: '2', label: 'STATE-LEVEL WINNER', detail: '1st Rank State-Level Product Engineering Competition in Smart Safety & IoT Solutions.' },
  { id: '3', label: 'RUNNER-UP AMONG 900+ PARTICIPANTS', detail: 'National Technical Prototype Hackathon top-tier distinction among 950+ participating engineering teams.' },
  { id: '4', label: 'PUBLISHED IN ELECTRONICS FOR YOU', detail: 'Featured technical research article and circuit design in Asia\'s leading electronics magazine.' },
  { id: '5', label: 'REAL PROTOTYPES', detail: '100% real, physically fabricated and field-tested hardware and software engineering systems.' },
];
