import { WorkProject, StudentProject, ServiceItem, ProcessStep, TeamMember } from './types';

export const WORK_PROJECTS: WorkProject[] = [
  {
    id: 'health-kiosk',
    title: 'Smart Privacy Health Kiosk',
    subtitle: 'An IoT-Enabled Automated System for Anonymous Access to Sensitive Healthcare Products',
    category: 'IoT Systems · Mechanical Design · Embedded Firmware · Product Innovation',
    tags: ['IoT Systems', 'Mechanical Design', 'Embedded Firmware', 'Product Innovation'],
    image: '/smart-health-kiosk.jpg',
    description: 'An IoT-enabled, privacy-first automated kiosk designed for 24×7 anonymous access to sensitive healthcare and wellness products (like sanitary pads, pregnancy test kits, and intimate care products), eliminating social stigma and judgment.',
    challenge: 'Designing an Automatic Privacy Packaging System (APPS) and a secure collection locker within a single deployable unit while maintaining reliable multilingual touchscreen control and cashless UPI payments.',
    solution: 'Engineered a custom internal packaging mechanism that bags products automatically before delivery, integrated fingerprint biometrics, RFID maintenance access, low-stock alerts, jam detection, and a remote IoT monitoring dashboard.',
    technologies: ['15-inch Touch UI', 'Automatic Packaging (APPS)', 'ESP32 / STM32', 'UPI Payment Integration', 'Fingerprint Biometrics', 'RFID Access'],
    outcomes: [
      'Awarded ₹2,30,000 PoC grant by SPU-SSIP Navadhārā',
      'Developed Automatic Privacy Packaging System (APPS) for discreet pickup',
      'Integrated 24x7 Emergency Pad Mode for dispensing when payment servers are down',
      'Built remote IoT dashboard for real-time inventory and predictive restocking',
    ],
    featured: true,
  },
  {
    id: 'agri-titan-x6',
    title: 'Agri-Titan X6',
    subtitle: 'Autonomous Precision Agriculture & Crop-Spraying Hexacopter',
    category: 'Drone Engineering · Embedded Systems · Agriculture Technology',
    tags: ['Drone Engineering', 'Embedded Systems', 'Agriculture Technology'],
    badge: 'SSIP-Funded Project',
    image: '/agri-titan-drone-2.png',
    description: 'Heavy-lift autonomous hexacopter drone equipped with multi-spectral NIR camera array and automated field waypoint mapping for targeted crop nutrition.',
    challenge: 'Achieving stable flight dynamics under 20kg payload conditions while maintaining precise flow-rate control synchronized with GPS ground speed.',
    solution: 'Designed carbon-fiber structural arm mounts, custom power distribution boards (PDB), and STM32 telemetry modules with real-time RTK-GPS correction.',
    technologies: ['Carbon Fiber DFM', 'ArduPilot / PX4', 'Custom High-Current PDB', 'LoRa Telemetry'],
    outcomes: ['Government SSIP Grant Recipient', '45% reduction in fertilizer usage during trials', 'Tested over 120 hectares of farmland'],
    featured: false,
  },
  {
    id: 'smart-print-station',
    title: 'SmartPrint Station',
    subtitle: 'IoT-Connected Cloud Kiosk for On-Demand Document Printing',
    category: 'Embedded Systems · Automation · Web Platform',
    tags: ['Embedded Systems', 'Automation', 'Web Platform'],
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80',
    description: 'Self-service unattended printing terminal allowing users to upload documents via WhatsApp or web link and pay via QR code for instant secure print releases.',
    challenge: 'Preventing paper jams, handling offline printer state machine errors, and encrypting document streams end-to-end.',
    solution: 'Built a ruggedized kiosk housing, custom micro-controller relay boards for power cycling, and cloud queue management with automatic document deletion after print.',
    technologies: ['Raspberry Pi 4', 'Python / Express', 'Thermal & Laser Automation', 'MQTT Protocol'],
    outcomes: ['99.8% uptime across university campuses', 'Processed over 180,000 print jobs', 'Zero paper loss security architecture'],
    featured: false,
  },
  {
    id: 'smart-safety-helmet',
    title: 'Smart Safety Helmet',
    subtitle: 'Industrial Worker IoT Protection & Hazardous Gas Detector',
    category: 'Hardware · Embedded Systems · Safety Technology',
    tags: ['Hardware', 'Embedded Systems', 'Safety Technology'],
    badge: 'State-Level Winning Project',
    image: '/smart-safety-helmet.jpg',
    description: 'Intelligent hard hat with impact detection, toxic gas monitoring (CO/Methane), optical thermal wear detection, and fall alerts connected to central site dashboards.',
    challenge: 'Ultra-low power constraints and lightweight ergonomic balancing for 12-hour continuous wear.',
    solution: 'Custom curved PCB fitting inside helmet shock absorption liners, Bluetooth Mesh mesh networking, and sub-100mW power consumption profile.',
    technologies: ['PCB Design (Altium)', 'BLE 5.2 / Mesh', 'IMU Fall Sensing', 'Gas Electro-Sensors'],
    outcomes: ['State-Level First Place Winner', 'Patented shock-absorption sensor mounting', 'Integrated into 3 industrial manufacturing plants'],
    featured: false,
  },
  {
    id: 'disinfection-robot',
    title: 'Autonomous Disinfection Robot',
    subtitle: 'Lidar-Guided UV-C & Spray Sterilization AGV',
    category: 'Robotics · Mechanical · Embedded Systems',
    tags: ['Robotics', 'Mechanical', 'Embedded Systems'],
    badge: 'R&D Initiative',
    image: '/disinfection-robot.png',
    description: 'Self-navigating sanitization robot equipped with LiDAR, ultrasonic collision avoidance, and automated high-output UV-C lamps for commercial facility disinfection.',
    challenge: 'Integrating sub-centimeter path accuracy, real-time obstacles mapping, and safety interlocks for UV-C exposure controls.',
    solution: 'Programmed navigation controllers in ROS, engineered dynamic path planner, and implemented fail-safe PIR presence detection triggers.',
    technologies: ['ROS (Robot Operating System)', 'LiDAR Navigation', 'ESP32 / Teensy', 'UV-C Array'],
    outcomes: ['Tested in 3 hospital wards', '99.9% pathogen elimination rate', 'Zero-human intervention operation'],
    featured: false,
  },
  {
    id: 'power-monitor',
    title: 'Smart Industrial Power Monitor',
    subtitle: 'Non-Invasive High-Accuracy Multi-Phase Current Logger',
    category: 'Electronics · Embedded Systems · Cloud Platform',
    tags: ['Electronics', 'Embedded Systems', 'Cloud Platform'],
    badge: 'Industrial IoT',
    image: '/power-monitor.png',
    description: 'Real-time IoT industrial power monitor using split-core current transformers, non-invasive load monitoring (NILM), and cloud analytics for power factor tracking.',
    challenge: 'Achieving sub-1% calibration accuracy for high-current ranges in electromagnetically noisy factory environments.',
    solution: 'Designed multi-layer noise-isolated analog front-end board, local storage cache, and secure AWS IoT MQTT telemetry pipeline.',
    technologies: ['Altium Designer', 'ARM Cortex-M4', 'Modbus/RS485', 'AWS IoT Core'],
    outcomes: ['Deployed across 8 factories', '14% average reduction in peak demand surcharges', 'Sub-second current telemetry'],
    featured: false,
  },
];

export const STUDENT_PROJECTS: StudentProject[] = [
  {
    id: 'iot-weather-station',
    title: 'Solar-Powered IoT Weather Station',
    category: 'Featured',
    difficulty: 'Intermediate',
    price: '$120',
    image: 'https://images.unsplash.com/photo-1590055531615-f16d36ffe8ec?auto=format&fit=crop&w=600&q=80',
    description: 'Complete DIY engineering kit with ESP32, anemometer, rain gauge, BME280 sensor, solar charging circuit, and custom React dashboard.',
    techStack: ['ESP32', 'C++', 'Solar MPPT', 'React Dashboard', 'MQTT'],
    includes: ['Custom Gerber Files & PCB', '3D Printable STL Files', 'Complete Source Code', 'Step-by-Step Circuit Guide'],
    specifications: {
      'Microcontroller': 'ESP32 Dual-Core Wi-Fi/BT',
      'Power System': '3.7V Li-Ion + 5W Solar Panel',
      'Sensors': 'Temp, Humidity, Pressure, Wind Speed, Rain Gauge',
      'Data Stream': 'ThingSpeak / Custom Web Dashboard',
    },
  },
  {
    id: 'robotic-arm-6dof',
    title: '6-DOF Programmable Robotic Arm',
    category: 'Popular',
    difficulty: 'Advanced',
    price: '$210',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=600&q=80',
    description: 'Precision inverse kinematics robotic arm kit with servo motor driver PCB, inverse kinematics Python library, and web interface.',
    techStack: ['Arduino Mega', 'Inverse Kinematics', 'WebSockets', '3D CAD Frame'],
    includes: ['Laser-Cut Acrylic & 3D Parts', 'PCA9685 Servo Driver PCB', 'Python Kinematics Script', 'Assembly Video Manual'],
    specifications: {
      'Payload Capacity': '350 grams at full extension',
      'Degrees of Freedom': '6 Servo Motors (MG996R)',
      'Control Mode': 'Joystick / Web GUI / Kinematic Recording',
      'Power Supply': '5V 10A DC Adapter',
    },
  },
  {
    id: 'smart-home-gateway',
    title: 'Offline Smart Home Automation Hub',
    category: 'New',
    difficulty: 'Beginner',
    price: '$85',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
    description: 'Local-first smart relay controller with voice control integration, local web portal, and zero external cloud dependence.',
    techStack: ['ESP8266 / ESP32', 'Relay Modules', 'WebSockets', 'HTML/JS Portal'],
    includes: ['Optocoupled Relay PCB', 'Enclosure STL File', 'Source Code & Firmware', 'Schematics PDF'],
    specifications: {
      'Channels': '4 Relay Outputs (10A 250VAC)',
      'Connectivity': 'Local Wi-Fi Access Point + Station',
      'Security': 'WPA2 Encryption + Token Auth',
      'Setup Time': 'Under 30 Minutes',
    },
  },
  {
    id: 'smart-plant-irrigation',
    title: 'Automated Soil Moisture & Drip Irrigation System',
    category: 'Featured',
    difficulty: 'Beginner',
    price: '$65',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80',
    description: 'Capacitive soil moisture sensing with solenoid valve control and OLED status display for automated home gardening.',
    techStack: ['Arduino Nano', 'Capacitive Sensor', 'Solenoid Valve', 'OLED Display'],
    includes: ['Custom Nano Shield PCB', 'Capacitive Moisture Sensor', 'Solenoid Driver Circuit', 'Code & Wiring Blueprint'],
    specifications: {
      'Sensor Type': 'Corrosion-Resistant Capacitive',
      'Power Input': '12V 2A DC Adapter',
      'Display': '0.96-inch Monochrome OLED',
      'Valve Rating': '12V DC 1/2-inch Solenoid',
    },
  },
  {
    id: 'gesture-glove-sign',
    title: 'Sign Language Translator Gesture Glove',
    category: 'Advanced',
    difficulty: 'Advanced',
    price: '$175',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80',
    description: 'Flex-sensor wearable glove with MPU6050 accelerometer and text-to-speech mobile app synchronization.',
    techStack: ['Flex Sensors', 'MPU6050 IMU', 'BLE 5.0', 'React Native App'],
    includes: ['Custom Flex Sensor Strips', 'Wearable ESP32 PCB', 'Mobile Companion App', 'ML Model Training Code'],
    specifications: {
      'Sensors': '5x Flex Sensors + 6-Axis Accelerometer/Gyro',
      'Wireless': 'Bluetooth Low Energy 5.0',
      'Accuracy': '94% Gesture Recognition Rate',
      'Battery Life': '8 Hours Active Use',
    },
  },
  {
    id: 'quadruped-robot-dog',
    title: 'Mini Quadruped Bionic Robot',
    category: 'Popular',
    difficulty: 'Advanced',
    price: '$240',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=600&q=80',
    description: '12-degree-of-freedom quadruped robot with gait generator, trot/walk algorithm, and remote Bluetooth controller.',
    techStack: ['STM32F4', '12 Servo Motors', 'Kinematics', 'Custom LiPo PDB'],
    includes: ['Precision 3D Printed Frame', '12x High-Torque Servos', 'Main Control Board', 'Gait Kinematics Firmware'],
    specifications: {
      'Gait Styles': 'Trot, Walk, Bounce, Dance',
      'Servos': '12x Metal Gear Digital Servos',
      'Processor': 'STM32F407 ARM Cortex-M4',
      'Weight': '820 grams',
    },
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: 'product-engineering',
    title: 'Product Engineering',
    description: 'End-to-end product architecture, feasibility analysis, system design, functional prototyping, and manufacturing preparation.',
    features: [
      'Discovery & Concept Feasibility',
      'System Architecture & Bill of Materials (BOM)',
      'Rapid Functional Prototyping',
      'Testing & Validation Protocols',
      'DFM (Design for Manufacturing) Handover',
    ],
    cta: 'Discuss a Product Idea →',
    iconName: 'Cpu',
  },
  {
    id: 'mechanical-cad',
    title: 'Mechanical Design & CAD',
    description: 'Industrial design, 3D CAD modeling, complex enclosure design, internal mechanisms, stress simulation, and 3D printing optimization.',
    features: [
      '3D Parametric CAD (SolidWorks/Fusion 360)',
      'Custom Enclosure & Mechanical Mounts',
      'FEA Stress & Thermal Simulation',
      'Tolerance Stackup Analysis',
      'Rapid Prototyping & CNC Machining Prep',
    ],
    cta: 'Start a Mechanical Project →',
    iconName: 'Boxes',
  },
  {
    id: 'electronics-pcb',
    title: 'Electronics & PCB',
    description: 'Custom PCB schematic capture, high-speed multi-layer layout, component selection, signal integrity, and circuit board assembly.',
    features: [
      'Schematic Capture & Component Sourcing',
      'Multi-Layer High-Density PCB Layout',
      'Power Management & Battery Circuits',
      'Sensor Integration & Signal Conditioning',
      'SMD Prototype Assembly & Testing',
    ],
    cta: 'Discuss an Electronics Project →',
    iconName: 'Zap',
  },
  {
    id: 'embedded-iot',
    title: 'Embedded Systems & IoT',
    description: 'Microcontroller firmware development, real-time operating systems (RTOS), IoT connectivity protocols, and sensor telemetry.',
    features: [
      'Firmware (ESP32, STM32, Nordic, Arduino)',
      'FreeRTOS & Embedded C/C++ Optimization',
      'BLE, Wi-Fi, LoRa, MQTT Protocols',
      'Over-The-Air (OTA) Firmware Updates',
      'Low-Power Sleep Modes & Battery Optimization',
    ],
    cta: 'Build an Embedded System →',
    iconName: 'Radio',
  },
  {
    id: 'software-development',
    title: 'Software Development',
    description: 'Full-stack web applications, custom management dashboards, cloud APIs, cross-platform mobile apps, and real-time control panels.',
    features: [
      'React / TypeScript Modern Web Apps',
      'Express & Node.js Backend Microservices',
      'Real-Time WebSocket Data Dashboards',
      'REST & GraphQL API Engineering',
      'Cloud Infrastructure & CI/CD Pipelines',
    ],
    cta: 'Discuss a Software Project →',
    iconName: 'Code2',
  },
  {
    id: 'ai-automation',
    title: 'AI & Automation',
    description: 'Computer vision integration, automated workflow pipelines, smart hardware edge-AI models, and generative AI features.',
    features: [
      'Computer Vision & Object Detection',
      'Edge AI Inference (TensorFlow Lite)',
      'Industrial Process Automation Pipelines',
      'Custom Gemini & LLM AI Integrations',
      'Predictive Maintenance Algorithms',
    ],
    cta: 'Explore AI Solutions →',
    iconName: 'Sparkles',
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: '01',
    title: 'DISCOVER',
    subtitle: 'Requirements & Product Roadmap',
    description: 'We analyze your core vision, evaluate physical and software constraints, establish performance targets, and map out the complete multidisciplinary project roadmap.',
    deliverables: ['Product Requirement Document (PRD)', 'Tech Stack Evaluation', 'Project Roadmap & Timeline'],
    shapeType: 'cube',
  },
  {
    number: '02',
    title: 'FEASIBILITY',
    subtitle: 'Proof of Concept & BOM Evaluation',
    description: 'We test core risk factors through quick benchtop prototypes, component sourcing verifications, and initial cost-of-goods (COGS) estimation.',
    deliverables: ['Benchtop Proof of Concept', 'Initial Bill of Materials (BOM)', 'Component Lead Time Audit'],
    shapeType: 'sphere',
  },
  {
    number: '03',
    title: 'ARCHITECT',
    subtitle: 'System & Circuit Design',
    description: 'We architect hardware schematics, PCB topologies, mechanical assembly structures, cloud database schemas, and firmware state machines.',
    deliverables: ['System Block Diagrams', 'Schematic Diagrams', '3D Layout Blueprint'],
    shapeType: 'torus',
  },
  {
    number: '04',
    title: 'DESIGN',
    subtitle: 'Industrial CAD & UI/UX Design',
    description: 'We shape the physical product enclosure for ergonomic compliance and design pixel-perfect digital interfaces for touchscreen displays or web portals.',
    deliverables: ['3D CAD Models (SolidWorks)', 'PCB Gerber Package', 'UI/UX Interactive Mockups'],
    shapeType: 'octahedron',
  },
  {
    number: '05',
    title: 'PROTOTYPE',
    subtitle: 'Physical Fabrication & Board Assembly',
    description: 'We 3D-print high-resolution enclosure prototypes, assemble custom SMD PCBs in-house, and flash early firmware builds for unit testing.',
    deliverables: ['Physical Enclosure Samples', 'Assembled Prototype Board', 'Base Firmware Flash'],
    shapeType: 'ring',
  },
  {
    number: '06',
    title: 'INTEGRATE',
    subtitle: 'Hardware-Software Mesh',
    description: 'We connect embedded sensors and microcontrollers with cloud servers, mobile control apps, and database pipelines to ensure end-to-end telemetry.',
    deliverables: ['Hardware-Cloud API Sync', 'Real-Time Control Panel', 'Over-The-Air (OTA) Channel'],
    shapeType: 'pyramid',
  },
  {
    number: '07',
    title: 'TEST & ITERATE',
    subtitle: 'Stress Testing & Quality Assurance',
    description: 'We execute thermal stress testing, drop tests, signal interference checks, edge-case firmware debugging, and performance optimization.',
    deliverables: ['Quality Assurance Test Report', 'Thermal & Stress Analysis', 'Refined Firmware Build'],
    shapeType: 'cylinder',
  },
  {
    number: '08',
    title: 'DELIVER',
    subtitle: 'Working Product & Handover',
    description: 'We deliver complete working hardware and software systems with full manufacturing documentation, source code, and deployment support.',
    deliverables: ['Working Product Units', 'Complete Manufacturing Package', 'Source Code & CAD Handover'],
    shapeType: 'knot',
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'prince-tagadiya',
    initials: 'PT',
    name: 'Prince Tagadiya',
    role: 'Founder, CEO & CPTO',
    department: 'Product · Technology · Business Strategy',
    tags: ['Product Strategy', 'Systems Architecture', 'Hardware R&D', 'Business Lead'],
    bio: 'Visionary engineering lead steering multidisciplinary hardware and software product creation from initial napkin sketch to scaled deployment.',
    expandedBio: 'Prince leads CRETO4\'s overall product roadmap, hardware-software architecture integration, and strategic client ventures. With deep expertise across cross-disciplinary engineering and industrial prototyping, he bridges conceptual client vision into robust physical products.',
    keyContributions: [
      'Architected the Smart Privacy Health Kiosk hardware & cloud pipeline',
      'Spearheaded SSIP Government Innovation Grant acquisition',
      'Directs multidisciplinary R&D across embedded, CAD, and software teams'
    ],
    specialties: ['Cross-disciplinary Systems Architecture', 'Industrial DFM & Rapid Prototyping', 'Venture Strategy & Client Delivery'],
    stats: [
      { label: 'Projects Led', value: '25+' },
      { label: 'R&D Experience', value: '4+ Yrs' },
      { label: 'Grants Secured', value: 'SSIP' }
    ]
  },
  {
    id: 'nisarg-patel',
    initials: 'NP',
    name: 'Nisarg Patel',
    role: 'Head of Electronics, Embedded Systems & Manufacturing',
    department: 'Hardware · Embedded · Electronics Manufacturing',
    tags: ['Hardware Engineering', 'Embedded C++', 'DFM', 'Sensors'],
    bio: 'Expert in high-reliability circuit design, power management, micro-controller firmware, and precision electronics manufacturing pipelines.',
    expandedBio: 'Nisarg leads the physical electronics engineering at CRETO4. From high-current power distribution boards for heavy-payload hexacopters to sub-second sensor telemetry hubs, he ensures ultra-reliable hardware performance under demanding operational environments.',
    keyContributions: [
      'Designed custom PDB and RTK-GPS telemetry for Agri-Titan X6 drone',
      'Developed sub-100mW power management for Smart Safety Helmet',
      'Established in-house SMT assembly & hardware verification protocols'
    ],
    specialties: ['STM32 & ESP32 Embedded C/C++', 'Power Electronics & Battery Systems', 'Sensor Telemetry & RF Communication'],
    stats: [
      { label: 'Custom PCBs', value: '40+' },
      { label: 'Sensor Modules', value: '100+' },
      { label: 'Uptime Rate', value: '99.9%' }
    ]
  },
  {
    id: 'khushi-belani',
    initials: 'KB',
    name: 'Khushi Belani',
    role: 'Head of PCB Design, Education & Brand Communications',
    department: 'PCB Design · Research · QA · Education · Brand',
    tags: ['PCB Layout', 'Signal Integrity', 'Quality Assurance', 'Brand Communication'],
    bio: 'Directs multi-layer PCB layout, component selection, educational project publishing, and technical brand positioning.',
    expandedBio: 'Khushi oversees high-density PCB design standards, electromagnetic compatibility (EMC) compliance, and technical publishing. She also leads CRETO4\'s educational STEM initiative, translating complex hardware designs into accessible learning kits for student engineers.',
    keyContributions: [
      'Published technical research articles in Electronics For You magazine',
      'Engineered multi-layer HDI PCB layouts for IoT diagnostic kiosks',
      'Curated DIY engineering kit documentation and Gerber manufacturing specs'
    ],
    specialties: ['Altium Designer Multi-Layer HDI Routing', 'Signal & Power Integrity Analysis', 'Technical Publishing & Brand Strategy'],
    stats: [
      { label: 'Publications', value: 'Featured' },
      { label: 'PCB Layers', value: '4-6 Layers' },
      { label: 'Kits Created', value: '15+' }
    ]
  },
  {
    id: 'rudra-chauhan',
    initials: 'RC',
    name: 'Rudra Chauhan',
    role: 'Head of Software Engineering & Digital Design',
    department: 'Software · Cloud Infrastructure · Digital Experiences',
    tags: ['Full-Stack Web', 'Cloud Infrastructure', '3D WebGL', 'AI Systems'],
    bio: 'Architects modern cloud applications, real-time IoT web portals, interactive 3D WebGL graphics, and scalable software backends.',
    expandedBio: 'Rudra directs the digital experience engineering at CRETO4. Combining full-stack React/Node web platforms with real-time hardware WebSockets, 3D WebGL visualizations, and modern AI/LLM API integrations, he delivers seamless software control for physical hardware devices.',
    keyContributions: [
      'Built full-stack real-time telemetry dashboard for Smart Health Kiosk',
      'Designed high-performance 3D WebGL interactive product visualizers',
      'Engineered zero-latency MQTT cloud queues for IoT print terminals'
    ],
    specialties: ['React / TypeScript / Vite / WebGL', 'Node.js, WebSockets & MQTT Telemetry', 'Cloud Infrastructure & API Design'],
    stats: [
      { label: 'Web Applications', value: '30+' },
      { label: 'Daily Telemetry', value: '50k+ Events' },
      { label: '3D Assets', value: 'Interactive' }
    ]
  }
];

export const TRUST_ACHIEVEMENTS = [
  { id: '1', label: 'SSIP FUNDED', detail: 'Government Student Startup & Innovation Policy Grant Recipient for Agriculture Drone Innovation.' },
  { id: '2', label: 'STATE-LEVEL WINNER', detail: '1st Rank State-Level Product Engineering Competition in Smart Safety & IoT Solutions.' },
  { id: '3', label: 'RUNNER-UP AMONG 900+ PARTICIPANTS', detail: 'National Technical Prototype Hackathon top-tier distinction among 950+ participating engineering teams.' },
  { id: '4', label: 'PUBLISHED IN ELECTRONICS FOR YOU', detail: 'Featured technical research article and circuit design in Asia\'s leading electronics magazine.' },
  { id: '5', label: 'REAL PROTOTYPES', detail: '100% real, physically fabricated and field-tested hardware and software engineering systems.' },
];
